# Generated by Django 4.2.7 on 2023-12-27 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cantor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Musicas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Dados_musicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streams', models.IntegerField(default=0, verbose_name='Número de Streams de uma música')),
                ('listeners', models.IntegerField(default=0, verbose_name='Número de Ouvintes')),
                ('view', models.IntegerField(default=0, verbose_name='Visualizações dessa música')),
                ('saves', models.IntegerField(default=0, verbose_name='Vezes que essa Música foi salva')),
                ('popularidade', models.IntegerField(default=0, verbose_name='Índice de popularidade')),
                ('musica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_control.musicas')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('cantor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_control.cantor')),
            ],
        ),
    ]
