# Generated by Django 4.2.7 on 2023-12-28 19:39

from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('music_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='musicas',
            field=models.ManyToManyField(to='music_control.musicas'),
        ),
        migrations.AddField(
            model_name='dados_musicas',
            name='data_captura',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='musicas',
            name='cantor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_control.cantor', default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popularidade', models.IntegerField(default=0, verbose_name='Índice de popularidade')),
                ('musica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_control.musicas')),
            ],
        ),
    ]
